#!/bin/bash
# Modules Source
if [ -n "$MODULEPATH" ]; then
  export MODULEPATH=/opt/moose/Modules/3.2.10/modulefiles
fi
source /opt/moose/Modules/3.2.10/init/$(basename $SHELL)

# MOOSE_PPS_WIDTH
export MOOSE_PPS_WIDTH=180

# Source the autojump profile if requested:
if [ -n "$MOOSE_JUMP" ]; then
  source /opt/moose/environments/autojump_profile
fi

# IF, anyone wants to use our prompt:
if [ -n "$MOOSE_PROMPT" ]; then
  PS1="\[\033[1;34m\][\u]\[\033[1;32m\][\w]\[\033[0m\]> "
fi

# Set MOOSE_JOBS and Load appropiate modules for Arch
if [[ `uname -s` == 'Darwin' ]] ; then
  export MOOSE_JOBS=`/usr/sbin/sysctl -n hw.ncpu`
  module load moose-dev-clang moose-tools
else
  export MOOSE_JOBS=`cat /proc/cpuinfo | grep processor | wc -l`
  module load moose-dev-gcc moose-tools
fi
