#!/bin/bash
if [ `uname -s` == 'Darwin' ]; then
# Set MOOSE_JOBS to the number of physical processors available
  export MOOSE_JOBS=`/usr/sbin/sysctl -n hw.ncpu`
else
  export MOOSE_JOBS=`cat /proc/cpuinfo | grep processor | wc -l`
fi

# TBB Source (TBB_DIR is needed by libMesh)
export TBB_DIR=/opt/moose/tbb
source $TBB_DIR/bin/tbbvars.sh intel64

# Modules Source
source /opt/moose/Modules/3.2.10/init/$(basename $SHELL)

# MOOSE_PPS_WIDTH
export MOOSE_PPS_WIDTH=180

# Source the autojump profile if requested:
if [ -n "$MOOSE_JUMP" ]; then
  source /opt/moose/environments/autojump_profile
fi

# IF, anyone wants to use our prompt:
if [ -n "$MOOSE_PROMPT" ]; then
  PS1="\[\033[1;34m\][\u]\[\033[1;32m\][\w]\[\033[0m\]> "
fi

# Load the moose-dev-clang and moose-tools module by default:
# module load moose-dev-clang moose-tools
