#!/bin/bash
#
# This file holds the instructions for updating the svn-system (and bash profile)
#
#update system files (previously embedded in svnupdate)
# 
# ** backup svn repo as follows:
# svnadmin dump /path/to/repo | gzip > backup.svn.gz
# ** load it back with:
# svnadmin create newrepos
# gunzip backup.svn.gz
# svnadmin load newrepos < backup.svn.gz

# sysupdate: update system-wide files {{{1
function sysupdate() { 
   echo "sysupdate:"   
   # mac only updates
   if [[ "$COMP_TYPE" == "local" ]] ; then
      # make sure that mac .bashrc opens .bash_profile
      if [[ ! -f $HOME/.bashrc ]] ; then
         echo "** no .bashrc file found on $HOSTNAME , creating one to point at ${BASH_PROFILE}"
         {
            echo '#!/bin/bash'
            echo '# source the .bash_profile file instead'
            echo 'source $HOME/.bash_profile'
         } > $HOME/.bashrc
      fi

      echo "** updated .muttrc and .mailcap"
      cp $SVN_BASH/muttrc $HOME/.muttrc
      chmod 600 $HOME/.muttrc
      cp $SVN_BASH/mailcap $HOME/.mailcap
            
      if [[ "x$(ls $HOME/.mutt/.imap_smtp)" == "x" ]] ; then
         echo "** ** no pass file found ... generating generic one"
         mkdir -p $HOME/.mutt
         printf  "set imap_pass = \"\"\nset smtp_pass = \"\"" > $HOME/.mutt/.imap_smtp
         chmod 600 $HOME/.mutt/.imap_smtp
      fi
      # gcalclirc file for google-calendar
      if [[ "x$(ls $HOME/.gcalclirc 2> /dev/null)" == "x"  ]] ; then
         echo "** creating .gcalclirc file, please add contact info"
         echo -ne "[gcalcli]\nuser:\npw:\n" > $HOME/.gcalclirc
      fi
      head -3 $HOME/.gcalclirc > $HOME/.gcalclirc.temp
      cat $SVN_BASH/gcalclirc >> $HOME/.gcalclirc.temp
      mv $HOME/.gcalclirc.temp $HOME/.gcalclirc
      chmod 600 $HOME/.gcalclirc
      echo "** updated .gcalclirc file"
      
      #X11 configuration
      cp $SVN_BASH/Xdefaults $HOME/.Xdefaults
      echo "** updated .Xdefaults file"

      # todo for todotxt
      mkdir -p $HOME/.todo
      cp $SVN_BASH/todo.cfg $HOME/.todo/config
      echo "** updated .todo/config"

      # gnuplot file
      cp $SVN_BASH/gnuplot $HOME/.gnuplot
      echo "** updated .gnuplot"

      # save lynxrc file
      cp $SVN_BASH/lynxrc $HOME/.lynxrc
      echo "** updated lynxrc file"
  fi

   # move tmux.conf to home directory for default use
   for file in $(ls ${SVN_BASH}/tmux.conf*)
   do
      cp $file $HOME/.${file##/*/}
   done
   echo "** updated .tmux.conf.*"

   # vimrc files
   #cp ${SVN_BASH}/vimrc $HOME/.vimrc
   #
   #if [[ $COMP_TYPE == "local" ]] ; then
      #rm -rf $HOME/.vim
      #rsync -r --exclude=.svn $SVN_BASH/vim $HOME
      #mv $HOME/vim $HOME/.vim
   #else
      #rm -rf $HOME/.vim
      #mkdir -p $HOME/.vim/colors
      #cp $SVN_BASH/vim/colors/* $HOME/.vim/colors
   #fi
   #echo "** updated .vimrc and .vim/{stuff}"

   # octave file
   cp $SVN_BASH/octaverc $HOME/.octaverc
   echo "** updated .octaverc"
      
   # colors
   cp $SVN_BASH/colors $HOME/.colors
   echo "** updated .colors"

   ## universal updates
   # make sure that the main profile file and vimrc profile are updated
   sed 's/SETUP_TIME_STAMP/ Updated: '"$(date)"'/g' ${SVN_BASH}/mainFile > ${BASH_PROFILE}
   echo "** time-stamp added to $BASH_PROFILE"

  # setup lammps
  #if [[ "x$(ls $LAMMPS_SRC 2> /dev/null)" == "x" ]] ; then
    #git clone http://git.icms.temple.edu/lammps-ro.git $LAMMPS_SRC
    #echo "** git clone LAMMPS [downloaded new]"
  #else
    #pushd . > /dev/null
    #echo "** attempting to update LAMMPS"
    #echo -n "  - "
    #cd $LAMMPS_SRC
    #{ git pull && echo "  - git pull LAMMPS [updated]" ; } || echo -e "${ERROR_RED}** error: could not 'git pull' in LAMMPS directory"
    #popd > /dev/null
  #fi
   
  # make sure that vim-tmp directory exists ... if not, make it
  if [[ "x$EDITOR_TMP" != "x" && ( ! -d $EDITOR_TMP || ! -d $EDITOR_TMP/backup ) ]] ; then
    echo "** making editor-tmp: $EDITOR_TMP"
    mkdir -p $EDITOR_TMP/backup
  fi

}

# svnupdate: update svn {{{1
function svnupdate() {
   # save original directory and go to SVN directory
   CURR=$PWD
   cd $MD_SVN
   echo "SVN update:"
   
   if [[ "$COMP_TYPE" == "local" ]] ; then
      # update svn data
      svn update --username $(hostname -s) --password kaeNagasaki
      
   else
      if [[ "$COMP_TYPE" == "remote" ]] ; then
         destination="$MD_CODE $MD_BIN $MD_CG $SVN_BASH"
      else
         destination="$SVN_BASH $MD_BIN"
      fi
      
      for directory in $destination ; do
                  
         # get the directory name
         subD=${directory#$MD_SVN/}
         subD=${subD#.}
         
         echo "  - $subD: updating "
         
         mkdir -p $directory
         cd $directory
         
         if [[ "x$(ls $directory/.svn)" != "x" ]] ; then
            svn update
         
         else
            # something is wrong with the directory, so we must purge it
            rm -r $directory

            if [[ "x$filesvn" == "x" ]] ; then
               svn co svn+ssh://cello/home/derekt/svnroot/${subD}/trunk/ $directory
            else
               svn co ${filesvn}/${subD}/trunk/ $directory
            fi
         fi
      done
   fi
   # return to origional directory
   cd $CURR

   # fixing back file permissions
   for dir in $(du $SVN_BASH | awk '{print $NF}') ; do 
      chmod 700 $dir
      for stuff in $(ls $dir) ; do 
         if [[ ! -d $dir/$stuff ]] ; then
            chmod 600 $dir/$stuff
         fi
      done
   done
   # now that svn is updated, update the sys files
   sysupdate   
}
if [[ "$HOSTNAME" == "cello3" ]] ; then
  function privateBash() {
  
    # fixing back file permissions                      
    for dir in $(du $SVN_BASH | awk '{print $NF}') ; do 
       chmod 700 $dir                                   
       for stuff in $(ls $dir) ; do                     
          if [[ ! -d $dir/$stuff ]] ; then              
             chmod 600 $dir/$stuff                      
          fi                                            
       done                                             
    done                                                
  }
fi


# compTypeName: Define the computer type on hostname {{{1
function compTypeName() {

   case $HOSTNAME in
      koguriyama.local | momo-castella.local ) 
         echo "local"
         ;;
      harp* | tuba* | mezzo* )
         echo "remote"
         ;;
      cello* )
         echo "central"
         ;;
      * )
         if [[ "$(uname)" == "Darwin" ]] ; then
            echo "local"
            exit 0
         fi
         echo "unkown"
         ;;
   esac
}
   
# Local-system specific functions {{{1o
if [ "$(compTypeName)" == "local" ] ; then
   # svnstatus: status of svn-root-directory  {{{2
   function svnstatus() {
      CURR=$PWD
      stat=$(svn status $MD_SVN)
    
      if [ "x$stat" == "x" ] ; then
         # exit with error status
         ! echo "svn status: no changes found"
      else
         echo "svn status:"
         echo -n "$stat"
         echo ""
      fi
      
   }
   
   # svnignore: ignore a directory or file that gets updated a lot  {{{2
   function svnignore() {
      echo "svnignore:"
      if [ "x$1" != "x" ] ; then
         svn propedit svn:ignore $1
      else
         echo "*** Please provide a file name or directory to ignore"
      fi
   }
   
   # svncia: commits a all svn subdirectories {{{2
   function svncia(){
      stopAll=1
      echo "svnciAll: $@"
      if [[ "x$@" == "x" ]] ; then
         tmp=$(mktemp /tmp/svncia.XXX)
         
         echo -ne "checking svn status ... \r"
         svnstatus > $tmp
         echo -ne "                        \r"

         # check if a commit is necessary
         if [[ $? -gt 0 ]] ; then
            echo "*** No commit necessary"
            stopAll=0
         fi
         
         # ask user if files should be added
         #cat $tmp | grep '?' | awk '{print $NF}'
         list=$(cat $tmp | grep '\?' | awk '{print $NF}')
         rm $tmp
         if [[ $stopAll -eq 1 ]] && [[ "x$(echo $list)" != "x" ]] ; then
            echo "-- $(echo $list | awk '{print NF}') unkown files exist in \$MD_SVN"
            i=1
            for file in $list ; do
               num=$(echo $i | awk '{printf "%3d",$1}')
               echo "$num: ${file#$MD_SVN}"
               while true ; do
                  read -p "   > add $(basename $file) (y/n)? " yn
                  case $yn in
                     [Yy]* ) svn add $file ; break ;;
                     [Nn]* ) break ;;
                     *     ) echo "*** Please answer yes or no?" ;;
                  esac
               done
               let i++
            done
         fi

         # now, we need to ask the user for svn commit memo
         if [[ stopAll -ne 0 ]] ; then
            svnstatus
            while true; do
               read -p "-- memo: " memo
               if [[ "x$memo" == "x" ]] ; then
                  echo "*** Please provide a useful log-memo"
               else
                  break
               fi
            done
         fi
      else
         memo="$@"
      fi

      # perform the commit
      if [[ $stopAll -ne 0 ]] ; then
         direc=$PWD
         cd $MD_SVN
         svn ci -m "$memo" \
            && growlnotify "SVN commit: All" -m "$memo"
         cd $direc
      fi

   }
   
   # SVN aliases {{{2
   alias cdsvn='cd $MD_SVN'
   alias svncoa='svn co svn+ssh://cello.t.u-tokyo.ac.jp/home/derekt/svnroot/'
   alias svnci='svn ci -m '   
fi
