#
# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.
#
#  Not all terminals support this and, of those that do,
#  not all provide facilities to test the support, hence
#  the user should decide based on the terminal type.  Most
#  terminals  support the  colours  black,  red,  green,
#  yellow, blue, magenta, cyan and white, which can be set
#  by name.  In addition. default may be used to set the
#  terminal's default foreground colour.  Abbreviations
#  are allowed; b or bl selects black.
#
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# these substitutions seem to cause problems with tmux AND, with vi-mode seem unnecessary
# WORDCHARS="${WORDCHARS:s#/#}"
# WORDCHARS="${WORDCHARS:s#.#}"

# define the specifc files needing sourcing (these are addresses relative to HOME)
sources=( ".zsh/color.zsh" ".zsh/keys.zsh" ".zsh/completion.zsh" ".zsh/profile.zsh" ".zsh/alias.zsh" ".zsh/prompt.zsh" ".zsh/functions.zsh")

# call the unity source
. $HOME/.unity/unity.sh

# auto extra zsh completion files
fpath=(~/.zsh/Completion $fpath)
fpath=(/usr/local/share/zsh-completions $fpath)

# This is a command that pipes all stderr to a red filter :)
# Compliments: http://skinwalker.wordpress.com/2012/01/24/stderr-zsh/

if [[ -f $HOME/.rcbundles/stderred/build/libstderred.dylib ]] ; then
    export DYLD_INSERT_LIBRARIES="$HOME/.rcbundles/stderred/build/libstderred.dylib${DYLD_INSERT_LIBRARIES:+:$DYLD_INSERT_LIBRARIES}"
    export STDERRED_ESC_CODE=$ERROR_RED
fi

[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
