#!/bin/bash

# define the specifc files needing sourcing (these are addresses relative to HOME)
sources=( ".colors" ".bash/profile.bash" ".bash/functions.bash" ".bash/alias.bash" ".bash/keys.bash" )
# call the unity source
. $HOME/.unity/unity.sh

if [ -f /opt/local/etc/profile.d/autojump.bash ]; then
    . /opt/local/etc/profile.d/autojump.bash
fi
if [ -f $HOME/local/bin/autojump.bash ] ; then
    . $HOME/local/bin/autojump.bash
fi
