#!/bin/bash

# define the specifc files needing sourcing (these are addresses relative to HOME)
sources=( ".colors" ".bash/profile.bash" ".bash/functions.bash" ".bash/alias.bash" ".bash/keys.bash" )
# call the unity source
. $HOME/.unity/unity.sh

